## Configuration of Hugo Website Theme

title: A. Jordan Nafa # Name of the Website
baseurl: 'https://www.ajordannafa.com/' # Base Website URL
copyright: '© 2021-{year} A. Jordan Nafa' # Footer text, e.g. '© {year} Me'

## Website Language Settings

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true


## Hugo Theme Modules

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

## Advanced Configuration Settings
publish_mode: editorial_workflow
enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  blog: "/blog/:year/:month/:day/:slug/"
  tags: "/blog/tags/:slug/"
  year: "/blog/:slug/"
  month: "/blog/:slug/"
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 100
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  research_type: research_type
  year: year
  month: month
markup:
  _merge: deep
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    style: monokai
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
