# Main Website Configuration Parameters

# Appearance
appearance:
  theme_day: meangreen
  theme_night: meangreen
  font: meangreen
  font_size: L

# SEO

site_type: Person
local_business_type: ''
org_name: 'University of North Texas, Department of Political Science'
description: 'A. Jordan Nafa is a Doctoral Candidate in the Department of Political Science at the University of North Texas'
twitter: 'adamjnafa'

# Contact Information

email: adamnafa@my.unt.edu
#phone: Uncomment this to add a phone number
address:
  street: 1121 Union Circle
  city: Denton
  region: TX
  postcode: '76201'
  country: United States
  country_code: US
coordinates:
  latitude: '33.210190'
  longitude: '-97.145579'
office_hours:
  - 'Monday 1:30 PM to 3:00 PM'
  - 'Friday 2:00 PM to 3:00 PM'
#appointment_url: 'https://calendly.com'
contact_links:
  - icon: twitter
    icon_pack: fab
    name: DM Me
    link: 'https://twitter.com/adamjnafa'
  - icon: linkedin
    icon_pack: fab
    name: Linked In
    link: 'https://linkedin.com/in/jordan-nafa-78599abb'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: true
  highlight_active_link: true

############################
## Code folding
############################

# Set to true to disable code folding
disable_codefolding: true
# Set to "hide" or "show" all codes by default
codefolding_show: "show"
# Set to true to exclude the "Show/hide all" button
codefolding_nobutton: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features
show_navbar: true

highlight: true
highlight_languages:
  - r
  - python
  - stan
highlight_style: "monokai"
math: true
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: false
  event: false
reading_time: false
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: 'disqus'
  commentable:
    post: true
    blog: true
    book: false
    project: false
    publication: false
    event: false
  disqus:
    shortname: 'ajordannafa'
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: ''
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'G-9M71770F2F'
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: true
icon:
  pack:
    ai: true
